Blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'blog'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

MyPersonalWebsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/',admin.site.urls),
    path("",include("MyPersonalWebsiteApp.urls",namespace="personalwebsite")),
    path("",include("Blog.urls",namespace="blog")),
]

MyPersonalWebsiteApp/urls.py
from django.urls import path
from . import views

app_name = "personal_website"

urlpatterns = [
    path ("profile/",views.Profile.as_view(),name="profile"),
    path ("about_me/",views.AboutMe.as_view(),name="about_me"),
    path ("projects/",views.Projects.as_view(),name="projects"),
    path ("contacts/reply/",views.Reply_on_message.as_view (),name="reply"),
    path ("",views.Index.as_view(),name="index"),
    path ("message/list/",views.MessageListView.as_view(),name="list"),
    path ("message/delete/<int:pk>", views.DeleteMessage.as_view(), name="delete"),
    path ("contacts/", views.Contacts.as_view(), name="contacts"),
]

Blog/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

MyPersonalWebsiteApp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

class Message(models.Model):
    email = models.EmailField ()
    phone = PhoneNumberField(null = True, blank = True)
    text = models.TextField(max_length=1000)
    created_date = models.DateTimeField(default=timezone.now)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.email

Blog/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

MyPersonalWebsiteApp/forms.py
from django import forms
from .models import Message

class BoardMessage (forms.ModelForm):

    def __init__(self, *args, **kwargs):
       super(BoardMessage, self).__init__(*args, **kwargs)
       self.fields['text'].widget.attrs={'id': 'textfield','placeholder': 'Please write your message here.','class':'col-sm form-field',}
       self.fields['email'].widget.attrs={'id': 'emailfield','placeholder': 'example@example.com','class':'col-sm form-control',}
       self.fields['phone'].widget.attrs={'id': 'phoneNumberField','placeholder': '+420 999 999 999','class':'col-sm form-control',}

    class Meta:
        model = Message
        fields = ("email","phone","text")

Blog/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import UserCreateForm
from .models import User

# Create your views here.
class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "blog/signup.html"
    model = User

MyPersonalWebsiteApp/views.py
from django.shortcuts import  render,get_object_or_404, redirect
from datetime import date
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView,FormView
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.conf import settings
import os
from django.db.models import Q
from django.utils import timezone
from django.conf import settings
from . import forms
from .models import Message
from .forms import BoardMessage
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.template import loader

class Contacts (CreateView):
    template_name = "message/contacts.html"
    form_class = BoardMessage
    model = Message
    success_url = 'reply/'    

    def form_valid(self, form):
        email=form.cleaned_data.get("email")
        phone=form.cleaned_data.get("phone")
        text=form.cleaned_data.get("text")
        body_sender=f"Greetings,\n\nthank you very much for your message:\n\n{text}.\n\nI will reply as soon as possible.\n\nThank you!\n\nBest regards\nTomas Richtr"
        body_admin=f"Greetings,\n\nYou got a new message on tomasr.pythonanywhere.com The message is:\n\n{text}.\n\nSender's phone is {phone}."

        send_mail(
            'tomasr.pythonanywhere.com: Your message was well received!',
            body_sender,
            '',
            [email],
            fail_silently=False,
        )

        send_mail(
            'You got a new message on tomasr.pythonanywhere.com!',
            body_admin,
            '',
            ["web.inner.cz@gmail.com"],
            fail_silently=False,
        )

        return super(Contacts, self).form_valid(form)      

class Index (TemplateView):

    template_name = "index.html"

class MessageListView(ListView):
    model = Message

    template_name = "message/message_list.html"

    ordering = ['-created_date']

class DeleteMessage(DeleteView):
    model = Message

    template_name = "message/delete.html"

    success_url = reverse_lazy("personal_website:list")

class Profile (TemplateView):

    template_name = "profile/profile.html"

class AboutMe (TemplateView):

    template_name = "about_me/about_me.html"

    def get(self, request, *args, **kwargs):
        born = date(1987, 6, 29)
        today = date.today()

        try:
            birthday = born.replace(year=today.year)
        except ValueError:
            birthday = born.replace(
                year=today.year, month=born.month + 1, day=1)

        if birthday > today:
            age = today.year - born.year - 1
        else:
            age = today.year - born.year

        context = {"age": age}

        return render(request, self.template_name, context)

class Projects (TemplateView):

    template_name = "projects/projects.html"

class Reply_on_message (TemplateView):

    template_name = "message/reply.html"


  

templates/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand menu-link" href="{% url 'personal_website:index' %}" title="Homescreen"><i class="fas fa-igloo fa-lg"></i></a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">

    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <li class="nav-item">
        <a class="nav-link menu-link active" href="https://www.linkedin.com/in/trichtr/" target="_blank"><i class="fab fa-linkedin fa-lg" title="LinkedIn"></i></a>
      </li>

      <li class="nav-item">
        <a class="nav-link menu-link active" href="https://github.com/TomRichtr" target="_blank"><i class="fab fa-github-square fa-lg" title="GitHub"></i></a>
      </li>

      <li class="nav-item dropdown">
          <a class="nav-link menu-link active" href="{% url 'personal_website:about_me' %}">About me</a>
      </li>
      <li class="nav-item">
        <a class="nav-link menu-link active" href="{% url 'personal_website:profile' %}">Profile</a>
      </li>

      <li class="nav-item">
        <a class="nav-link menu-link active" href="{% url 'personal_website:projects' %}">Projects</a>
      </li>

      <li class="nav-item">
        <a class="nav-link disabled menu-link" href="{% url 'personal_website:projects' %}">Blog</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link menu-link contacts active" href="{% url 'personal_website:contacts' %}">Contacts</a>
      </li>

    </ul>

    <ul class="navbar-nav mr-right mt-2 mt-lg-0">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link menu-link active"> &nbsp;{{user.email}}&nbsp; <i class="fas fa-user-alt fa-lg" title="Welcome: {{user.username}}"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link menu-link active" href="{% url 'blog:logout' %}"><i class="fas fa-sign-out-alt fa-lg" title="Log Out"></i></a>
      </li>
    {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link menu-link active" href="{% url 'personal_website:list' %}"><i class="fas fa-list-alt fa-lg" title="Message List"></i></a>
      </li>
    {% endif %}
    {% else %}
      <li class="nav-item">
        <a class="nav-link menu-link active" href="{% url 'blog:login' %}"><i class="fas fa-sign-in-alt fa-lg" title="Log In"></i></a>
      </li>
    {% endif %}
    </ul>
  </div>
</nav>

templates/abilities/_languages.html
{% load static %}

<div class="row">
  <div class="col-sm-6 rating-container czech d-flex justify-content-between">
    <div class="skill-name-container">Czech</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container english d-flex justify-content-between">
    <div class="skill-name-container">English</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container german d-flex justify-content-between">
    <div class="skill-name-container">German</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container d-flex justify-content-between">
    <div></div>
    <div class="">
    </div>
  </div>
</div>

templates/abilities/_skills.html
{% load static %}

<div class="row">
  <div class="col-sm-6 rating-container html d-flex justify-content-between">
    <div class="skill-name-container">HTML5</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container css d-flex justify-content-between">
    <div class="skill-name-container">CSS3</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container js d-flex justify-content-between">
    <div class="skill-name-container">Java Script</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container jq d-flex justify-content-between">
    <div class="skill-name-container">jQuery</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container react d-flex justify-content-between">
    <div class="skill-name-container">React JS</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container redux d-flex justify-content-between">
    <div class="skill-name-container">Redux</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container python d-flex justify-content-between">
    <div class="skill-name-container">Python3</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container django d-flex justify-content-between">
    <div class="skill-name-container">Django</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container bootstrap d-flex justify-content-between">
    <div class="skill-name-container">Bootstrap4</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container git d-flex justify-content-between">
    <div class="skill-name-container">Git</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container postgresql d-flex justify-content-between">
    <div class="skill-name-container">PostgreSQL</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container github d-flex justify-content-between">
    <div class="skill-name-container">Github</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

templates/abilities/_tools.html
{% load static %}

<div class="row">
  <div class="col-sm-6 rating-container atom d-flex justify-content-between">
    <div class="skill-name-container">Atom</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container vs d-flex justify-content-between">
    <div class="skill-name-container">MS VS</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container sublime d-flex justify-content-between">
    <div class="skill-name-container">Sublime Text3</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container jupyter d-flex justify-content-between">
    <div class="skill-name-container">Jupyter Notebook</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container pga d-flex justify-content-between">
    <div class="skill-name-container">PG Admin4</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container gitbash d-flex justify-content-between">
    <div class="skill-name-container">Github app</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container msoffice d-flex justify-content-between">
    <div class="skill-name-container">Word, OL, PPT</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
  <div class="col-sm-6 rating-container msexcel d-flex justify-content-between">
    <div class="skill-name-container">MS Excel</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 rating-container firefox d-flex justify-content-between">
    <div class="skill-name-container">Firefox</div>
    <div class="">
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
      <span class="fa fa-star"></span>
    </div>
  </div>
</div>

templates/about_me/_certificates.html
{% load static %}

<h5 class="sub-title-details">Certificates</h5>
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators" id="education">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'pictures\UC-b9233f29-e19a-498f-8caf-5b18fc612e89.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'pictures\UC-c85d25e5-0225-4e1b-82ba-a6b67b022cf1.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'pictures\UC-714bedaa-cbec-4edd-a1bc-bdf593a697b7.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'pictures\UC-8533346a-275f-4c40-ad3b-4eb318f1a1bc.jpg' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

templates/about_me/_courses.html
{% load static %}

<h5 class="sub-title-details">Courses</h5>
<div class="row">
  <div class="col-sm-3 text">
    <p class="text text-left"><strong>Jul 2020</strong></p>
  </div>
  <div class="col-sm-9 text">
    <p class="text text-left top-line">Udemy<i class="fas fa-grip-lines-vertical"></i>&nbsp; <a href="http://ude.my/UC-8533346a-275f-4c40-ad3b-4eb318f1a1bc" class="text place" target="_blank"><i class="fas fa-external-link-alt"></i>Credential URL</a></p>
    <p class="text text-left">The Complete React Developer Course (w/ Hooks and Redux)</p>
    <p class="text text-left">Credential ID: UC-8533346a-275f-4c40-ad3b-4eb318f1a1bc</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-3 text">
    <p class="text text-left"><strong>Jun 2020</strong></p>
  </div>
  <div class="col-sm-9 text">
    <p class="text text-left top-line">Udemy<i class="fas fa-grip-lines-vertical"></i>&nbsp; <a href="http://ude.my/UC-b9233f29-e19a-498f-8caf-5b18fc612e89" class="text place" target="_blank"><i class="fas fa-external-link-alt"></i>Credential URL</a></p>
    <p class="text text-left">Python and Django Full Stack Web Developer Bootcamp</p>
    <p class="text text-left">Credential ID: UC-b9233f29-e19a-498f-8caf-5b18fc612e89</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-3 text">
    <p class="text text-left"><strong>Jun 2020</strong></p>
  </div>
  <div class="col-sm-9 text">
    <p class="text text-left top-line">Udemy<i class="fas fa-grip-lines-vertical"></i>&nbsp; <a href="http://ude.my/UC-c85d25e5-0225-4e1b-82ba-a6b67b022cf1" class="text place" target="_blank"><i class="fas fa-external-link-alt"></i>Credential URL</a></p>
    <p class="text text-left">Complete Python 3 Bootcamp</p>
    <p class="text text-left">Credential ID: UC-c85d25e5-0225-4e1b-82ba-a6b67b022cf1</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-3 text">
    <p class="text text-left"><strong>Apr 2020</strong></p>
  </div>
  <div class="col-sm-9 text">
    <p class="text text-left top-line">Udemy<i class="fas fa-grip-lines-vertical"></i>&nbsp; <a href="http://ude.my/UC-714bedaa-cbec-4edd-a1bc-bdf593a697b7" class="text place" target="_blank"><i class="fas fa-external-link-alt"></i>Credential URL</a></p>
    <p class="text text-left">Complete SQL Bootcamp</p>
    <p class="text text-left" id="certificates">Credential ID: UC-714bedda-cbec-4edd-a1bc-bdf593a697b7</p>
  </div>
</div>

templates/about_me/_intro.html
{% load static %}

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h5 class="sub-title">A starting web-application developer</h5>
        <p class="text">Just recently I have decided to make a quite a turn and become an web-application developer.
        Ever since I am trying to get into programming as fast I can. To learn which languages and tools I am
        trying to get into and how I am doing, please refer to profile.</p>
    </div>
    <div class="col-sm-6 col-md-6">
        <h5 class="sub-title">Details</h5>
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{% static 'pictures\fotoprome.cz-13533_2133_sep.jpg' %}" height="100%" class="card-img" alt="personal photo">
                </div>
                <div class="col-md-8 details-container">
                    <div>
                        <p class="text text-center"><strong>Name: </strong>Tomáš Richtr</p>
                    </div>
                    <div>
                        <p class="text text-center"><strong>Age: </strong>{{age}}</p>
                    </div>
                    <div>
                        <p class="text text-center"><strong>Location: </strong>Prague</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/about_me/about_me.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="row">
  <div class="col-sm col-md col-lg-2"></div>

  <div class="col-sm-12 col-md-12 col-lg">
    <div class="jumbotron jumbotron-fluid regular-pages">
      <div class="container">
      <h1 class="page-title">About me</h1>
        {% include "about_me/_intro.html" %}
      </div>
    </div>
  </div>

  <div class="col-sm col-md col-lg-2"></div>
</div>

{% endblock %}

templates/blog/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-sm col-md col-lg-2"></div>
  <div class="col-sm-12 col-md-12 col-lg">
    <div class="jumbotron jumbotron-fluid regular-pages">
      <h1 class="page-title">Please log-in:</h1>
      <h5 class="sub-title authentication"></h5>
      {% if form.errors %}
      <div class="alert-danger" role="alert">Your username and password didn't match. Please try again!</div>
      {% endif %}
      <form method="POST" action="{% url 'blog:login' %}">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class='btn btn-secondary btn-lg btn-block' value="Login" />
      </form>
      <a href="{% url 'blog:signup' %}"><button class='btn btn-secondary btn-lg btn-block sign-up-button' value="SignUp">Doesn´t have an account yet? Sign up.</button></a>
    </div>
  </div>
  <div class="col-sm col-md col-lg-2"></div>
</div>

{% endblock %}

templates/blog/signup.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-sm col-md col-lg-2"></div>
  <div class="col-sm-12 col-md-12 col-lg">
    <div class="jumbotron jumbotron-fluid regular-pages">
      <h1 class="page-title">Please sign-up:</h1>
      <h5 class="sub-title authentication"></h5>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" name="" value="Submit" class="btn btn-secondary btn-lg btn-block">
      </form>
    </div>
  </div>
  <div class="col-sm col-md col-lg-2"></div>
</div>

{% endblock %}

templates/message/_message_form.html
{% load static %}
{% load crispy_forms_tags %}


<form enctype="multipart/form-data" method="POST">
  {% csrf_token %}
  {{ form.email|as_crispy_field }}
  {{ form.phone|as_crispy_field }}
  {{ form.text|as_crispy_field }}
  <p id="characters"><p>
  <input type="submit" name="" value="Submit" class="btn btn-secondary btn-lg btn-block">
</form>

templates/message/message_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-sm col-md col-lg-2"></div>
  <div class="col-sm-12 col-md-12 col-lg">
    <h1 class="page-title message-list">Message list</h1>
    {% for message in object_list %}
    <h5 class="sub-title"></h5>
    <div class="card">
      <h5 class="card-header">{{message.email}} / {{message.phone}}</h5>
      <div class="card-body">
        <h5 class="card-title">{{message.created_date}}</h5>
        <p class="card-text">{{message.text}}</p>
        <a href="{% url 'personal_website:delete' message.id %}" class="btn btn-secondary btn-lg btn-block">Delete</a>
      </div>
    </div>
    {% empty %}
    <h5 class="sub-title">No messages available.</h5>
    {% endfor %}
  </div>
  <div class="col-sm col-md col-lg-2"></div>
</div>
{% endblock %}